### ISSUE TITLE
Not a Buffer

### ISSUE THREAD

**Issue by prescottprue** [flyingsparx/NodeDirectUploader#2]
Getting : `TypeError: Not a buffer
<br> &nbsp; &nbsp;at new Hmac (crypto.js:226:17)
    <br> &nbsp; &nbsp;at Object.Hmac (crypto.js:224:12)
        <br> &nbsp; &nbsp;at app.post.username (/Users/scott/Code/NodeDirectUploader/app.js:58:28)
            <br> &nbsp; &nbsp;at callbacks (/Users/scott/Code/NodeDirectUploader/node_modules/express/lib/router/index.js:164:37)
                <br> &nbsp; &nbsp;at param (/Users/scott/Code/NodeDirectUploader/node_modules/express/lib/router/index.js:138:11)
                    <br> &nbsp; &nbsp;at pass (/Users/scott/Code/NodeDirectUploader/node_modules/express/lib/router/index.js:145:5)
                        <br> &nbsp; &nbsp;at Router._dispatch (/Users/scott/Code/NodeDirectUploader/node_modules/express/lib/router/index.js:173:5)
                            <br> &nbsp; &nbsp;at Object.router (/Users/scott/Code/NodeDirectUploader/node_modules/express/lib/router/index.js:33:10)
                                <br> &nbsp; &nbsp;at next (/Users/scott/Code/NodeDirectUploader/node_modules/express/node_modules/connect/lib/proto.js:169:15)
                                    <br> &nbsp; &nbsp;at SendStream.error (/Users/scott/Code/NodeDirectUploader/node_modules/express/node_modules/connect/node_modules/serve-static/index.js:88:7)`

When trying to test get request to /sign_s3 with both url parameters(s3_object_name and s3_object_type) filled. I believe it has something to do with the put_request string being the incorrect format.

**Comment by willwebberley** [comment]
Hi,
I do not know what your code looks like, but I assume you mean that the following line is giving you trouble?
`var signature = crypto.createHmac('sha1', AWS_SECRET_KEY).update(put_request).digest('base64');`

If so, then it may be that Node isn't loading your `AWS_SECRET_KEY` correctly. Try placing a check somewhere above this line to see if this variable is being properly set. If not, then it may be something to do with the `put_request`, as you say. I haven't heard of people having this issue before, which is why I'm more inclined to think it's to do with your AWS secret key!
