### ISSUE TITLE
Getting Error "Error: Request failed with status code 404" trying to load the file to S3

### ISSUE THREAD

**Issue by d3non** [flyingsparx/NodeDirectUploader#20]
I get a correct and successful S3 Signed JSON from S3, but when i try to do the PUT to my Bucket it throws "Error: Request failed with status code 404", any idea of what could be the problem?. Thank's

**Comment by willwebberley** [comment]
Hi, I'll need a little more info about this to help diagnose the problem. Can you let me know what the PUT request URL looks like (i.e. you can obscure the signature details)? Can you also check that the bucket exists, etc.

Also, sometimes S3 can be picky about how it is addressed (and may require you to use, for example, `<bucketname>.s3.amazonaws.com` rather than something containing your region).

**Comment by d3non** [comment]
Hi, thank you for your reply, i fixed the error by configuring in my S3 dashboard the correct access to my bucket, it was a matter of permissions. Thanks again!
